#!/bin/bash

if [ -z $SNAKEFILE ]; then
    SNAKEFILE=$1
fi

if [ -z $EXTRA ]; then
    EXTRA=$2
fi


(source activate lcdb-wf; \
    time snakemake \
    -p \
    -s $SNAKEFILE \
    --directory $PWD \
    -T \
    --rerun-incomplete \
    --jobname "s.{rulename}.{jobid}.sh" \
    -j 999 \
    --cluster-config clusterconfig.yaml \
    --verbose \
    --cluster 'sbatch {cluster.prefix} --cpus-per-task={threads} ' \
    --use-conda \
    --configfile config.yml \
    --latency-wait=60 \
    $EXTRA \
    ) > "${SNAKEFILE}.log" 2>&1
