sampletable: 'config/sampletable.tsv'

# See https://rnabio.org/module-09-appendix/0009/12/01/StrandSettings for more info.
stranded: 'fr-firststrand'     # for dUTP libraries
#         'fr-secondstrand'    # for ligation libraries
#         'unstranded'         # for libraries without strand specificity
