# Anything to the right of these extensions is removed when generating sample
# names.  Note that removing .cutadapt (and therefore effectively merging
# .cutadapt.bam with .cutadapt.fastq.gz and .fastq.gz) is OK because below
# we're running FastQC on them separately
#
# See http://multiqc.info/docs/#sample-name-cleaning
extra_fn_clean_exts:
  - '.cutadapt'
  - ']'
  - '.log'
  - '.bam.bowtie2'
  - '.gz'
  - '.fastq'
  - '.salmon'
  - '_R1'
  - '_R2'


# Ignore the rRNA files, which were just cluttering the tables. We're
# independently calculating the rRNA libsizes anyway, so there's no need for
# them to be included.
#
# See http://multiqc.info/docs/#ignoring-files
fn_ignore_files:
  - '*rrna.bam*'

# Set the module order to reflect the order of the workflow. Note that here
# we're also running the FastQC module multiple times, and putting them in
# their logical locations within the order of the workflow.
#
# Note that any modules not found on this list float
# to the top, so if you add more to the workflow, might want to add them in the
# right place here.
#
# See http://multiqc.info/docs/#order-of-modules
module_order:
    - fastqc:
        name: 'FastQC (raw R1)'
        path_filters_exclude:
            - '*_R2*'
            - '*_R1.cutadapt.fastq.gz_fastqc.zip'
        path_filters:
            - '*_R1.fastq.gz_fastqc.zip'
    - fastqc:
        name: 'FastQC (raw R2)'
        path_filters_exclude:
            - '*_R1*'
            - '*_R2.cutadapt.fastq.gz_fastqc.zip'
        path_filters:
            - '*_R2.fastq.gz_fastqc.zip'
    - rrna_percentages_table
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed R1)'
        target: ''
        path_filters_exclude:
            - '*_R2*'
        path_filters:
            - '*_R1.cutadapt.fastq.gz_fastqc.zip'
    - fastqc:
        name: 'FastQC (trimmed R2)'
        target: ''
        path_filters_exclude:
            - '*_R1*'
        path_filters:
            - '*_R2.cutadapt.fastq.gz_fastqc.zip'
    - fastq_screen
    - bowtie2
    - fastqc:
        name: 'FastQC (aligned)'
        target: ''
        path_filters:
            - '*.cutadapt.bam_fastqc.zip'
    - picard
    - rseqc
    - salmon
    - featurecounts:
        name: 'featureCounts'
        path_filters:
            - 'featurecounts.txt.summary'

remove_sections:
  - fastqc_status_checks


# This organizes the FastQC general sample table columns so that the different
# stages are right next to each other, making it easier to compare the effects
# of the different stages on the stats.
#
# See http://multiqc.info/docs/#customising-tables
table_columns_name:
  FastQC (raw R1):
    total_sequences: "Seq (raw R1)"
    percent_duplicates: "Dups (raw R1)"
    percent_gc: "GC (raw R1)"
  FastQC (raw R2):
    total_sequences: "Seq (raw R2)"
    percent_duplicates: "Dups (raw R2)"
    percent_gc: "GC (raw R2)"
  FastQC (trimmed R1):
    total_sequences: "Seq (trim R1)"
    percent_duplicates: "Dups (trim R1)"
    percent_gc: "GC (trim R1)"
  FastQC (trimmed R2):
    total_sequences: "Seq (trim R2)"
    percent_duplicates: "Dups (trim R2)"
    percent_gc: "GC (trim R2)"
  FastQC (aligned):
    total_sequences: "Seq (aligned)"
    percent_duplicates: "Dups (aligned)"
    percent_gc: "GC (aligned)"

table_columns_placement:
  FastQC (raw R1):
    total_sequences: 20
    percent_duplicates: 30
    percent_gc: 40
  FastQC (raw R2):
    total_sequences: 21
    percent_duplicates: 31
    percent_gc: 41
  FastQC (trimmed R1):
    total_sequences: 22
    percent_duplicates: 32
    percent_gc: 42
  FastQC (trimmed R2):
    total_sequences: 23
    percent_duplicates: 33
    percent_gc: 43
  FastQC (aligned):
    total_sequences: 24
    percent_duplicates: 34
    percent_gc: 44
