hub:
  name: 'example-rnaseq'
  short_label: 'example-rnaseq'
  long_label: 'example-rnaseq'
  email: 'dalerr@niddk.nih.gov'
  genome: 'dm6'
  url: 'https://example.com/hub.txt'
  remote_fn: '/www-data/trackhub/hub.txt'

upload:
  host: localhost
  user: $USER
  rsync_options: '-vprLt --progress'
  staging: staging

subgroups:
  # The subgroups to use, as specified in sampletable.tsv. The order matters;
  # they will be used to create dimensions.
  columns:
    - group
    - samplename

  # the default sort order can be independent of the columns. Anything missing
  # here will inherit sorting from `columns` above.
  sort_order:
    - samplename

# Colors and regular expressions to search against samplenames. These use `regex.search`
# instead of `regex.match`, so if the pattern can be found anywhere. 
#
# Note that this is a list of one-key dicts. The list is prioritized such that
# the first pattern to match a sample wins. The value of each single-value dict
# is itself a list, so you can easily group tracks by color.
colors:
  - "#4c9985":
    - control
  - "#003366":
    - treatment
