hub:
  name: 'exampleexperient'
  short_label: 'Example experiment'
  long_label: 'Example experiment'
  email: 'dalerr@niddk.nih.gov'
  genome: 'mmci'dm610'
  url: 'http://host/path/hub.txt'

upload:
  host: example.com
  user: username
  rsync_options: '-vprLt --progress'
  staging: staging
  remote_dir: '/path/on/host'

subgroups:
  # The subgroups to use, as specified in sampletable.tsv. The order matters;
  # they will be used to create dimensions.
  columns:
    - group
    - samplename

  # the default sort order can be independent of the columns. Anything missing
  # here will inherit sorting from `columns` above.
  sort_order:
    - samplename

# Colors and regular expressions to search against samplenames. These use `regex.search`
# instead of `regex.match`, so if the pattern can be found anywhere. 
#
# Note that this is a list of one-key dicts. The list is prioritized such that
# the first pattern to match a sample wins. The value of each single-value dict
# is itself a list, so you can easily group tracks by color.
colors:
  - "#4c9985":
    - control
  - "#003366":
    - treatment


# Each dict in the supplemental list will be added to the track hub, under the
# "supplemental view". The dict is passed directly to trackhub.Track(), so
# anything valid there is also valid here.
supplemental:
  -
    name: "myprimers"
    short_label: "primers"
    long_label: "primers for experiment 1"
    tracktype: "bigBed"
    source: "supplemental/primers.bigbed"
    color: "255,0,0"
    visibility: "dense"
