#!/bin/bash
#SBATCH --job-name="lcdb-wf"
#SBATCH --partition="norm"
#SBATCH --time=12:00:00
#SBATCH --gres=lscratch:5

# make logdir
if [[ ! -e logs ]]; then mkdir -p logs; fi

# Run snakemake
(
    time snakemake \
    -p \
    --directory $PWD \
    -k \
    --rerun-incomplete \
    --jobname "s.{rulename}.{jobid}.sh" \
    -j 999 \
    --use-conda \
    --configfile config/config.yaml \
    --latency-wait=300 \
    --max-jobs-per-second 1 \
    --max-status-checks-per-second 0.01 \
    "$@"
    ) > "Snakefile.log" 2>&1

SNAKE_PID=$!

finish(){
    echo 'Stopping running snakemake job.'
    kill -SIGINT $SNAKE_PID
    exit 0
}
trap finish SIGTERM

wait $SNAKE_PID
