#!/bin/bash
#SBATCH --job-name="lcdb-wf"
#SBATCH --partition="niddk,norm"
#SBATCH --time=24:00:00

SNAKEFILE=$1

if [ -z $2 ]; then
    EXTRA=$2
else
    EXTRA=''
fi


# make logdir
if [[ ! -e logs ]]; then mkdir -p logs; fi

# Run snakemake
(source activate lcdb-wf; \
    time snakemake \
    -p \
    -s $SNAKEFILE \
    --directory $PWD \
    -T \
    -k \
    --rerun-incomplete \
    --jobname "s.{rulename}.{jobid}.sh" \
    -j 999 \
    --cluster-config config/clusterconfig.yaml \
    --verbose \
    --cluster 'sbatch {cluster.prefix} --cpus-per-task={threads}  --output=logs/{rule}.o.%j --error=logs/{rule}.e.%j' \
    --use-conda \
    --configfile config/config.yml \
    --latency-wait=60 \
    $EXTRA \
    ) > "${SNAKEFILE}.log" 2>&1

SNAKE_PID=$!

finish(){
    echo 'Stopping running snakemake job.'
    kill -SIGINT $SNAKE_PID
    exit 0
}
trap finish SIGTERM

wait $SNAKE_PID
