sampletable: 'config/sampletable.tsv'

genome:
  url: "https://raw.githubusercontent.com/lcdb/lcdb-test-data/master/data/seq/dm6.small.fa"
  postprocess: 'lib.utils.gzipped'

chipseq:
  # The peak_calling section is a list of dicts, each one defining a single
  # chipseq peak-calling run. The output will be created according to `label`
  # and `algorithm`. There will be at least a file
  # `<peaks_dir>/<algorithm>/<label>/peaks.bed`; other files may be created
  # depending on the algorithm.
  #
  # Note that this directory structure means you can have the same label for
  # different peak-callers to more easily compare them.
  #
  # The `ip` and `control` sections expect names found in the "label" column of
  # the sampletable. This column describes the technical replicates, and the
  # merging step of the workflow merges and de-dupes appropriately so that the
  # peak callers only see BAMs with all duplicates removed.
  #
  # Each wrapper is built to accept either single or multiple BAMs and output
  # at least a BED file of peaks.
  #
  peak_calling:

    - label: gaf-embryo-1
      algorithm: macs
      ip:
        - gaf-embryo-1
      control:
        - input-embryo-1
      # optional user-specified override mappable genome size if specified
      # here, MACS will use this value instead of the value specific to the
      # genome build if NOT specified here, MACS will use the mappability value
      # for your genome build
      effective_genome_count: 7e7
      extra: '--nomodel --extsize 147'

    - label: gaf-wingdisc-pooled
      algorithm: macs
      ip:
        - gaf-wingdisc-1
        - gaf-wingdisc-2
      control:
        - input-wingdisc-1
        - input-wingdisc-2
      extra: '--nomodel --extsize 147'

    - label: gaf-wingdisc-pooled-1
      algorithm: epic2
      ip:
        - gaf-wingdisc-1
      control:
        - input-wingdisc-1
      extra: ''

    - label: gaf-wingdisc-pooled-2
      algorithm: epic2
      ip:
        - gaf-wingdisc-2
      control:
        - input-wingdisc-2
      extra: ''

    - label: gaf-wingdisc-pooled-3
      algorithm: epic2
      ip:
        - gaf-wingdisc-1
        - gaf-wingdisc-2
      control: []
      extra: ''
